# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Checkin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 */12 * * *

jobs:

  Yuki-Glados-Checkin:
    runs-on: windows-latest
    env:
      EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
    steps:
    - uses: actions/checkout@v3

    - name: Run
      run: ./checkin.exe ${{ secrets.KOASESS }} ${{ secrets.KOASESSSIG }} ${{ secrets.EMAIL }}
